### PR TITLE
mansoor_homework

### PR DESCRIPTION
**Pull request by mansoor81**
made some changes

### CODE REVIEW

**Review by RuslanIbrahimov — CHANGES_REQUESTED** [review]
needs some changes

**Review by WaseemZ — CHANGES_REQUESTED** [review]
Please create a file with your name as it and also put an image under that file.

**Review by mansoor81 — COMMENTED** [review]
whats up

**Review by mansoor81 — COMMENTED** [review]
hey

**Review by RoseKamontip — APPROVED** [review]
awesome !!!

**Review by dolkun615 — APPROVED** [review]
awesome work. keep on.

**Review by marat25 — APPROVED** [review]
100% Approved!!!

**Pull request merged**
